business.train = read.csv("yelp_academic_dataset_business_train.csv", header = TRUE)
business.test = read.csv("yelp_academic_dataset_business_test.csv", header = TRUE)
business = rbind(business.train[,-14], business.test[,-2])
library("qdapRegex")
attributes <- business$attributes
rm_all_except_letters <- rm_(pattern="[^ a-zA-Z]")

attributes.new <- rm_all_except_letters(attributes)
attri_Alcohol <- rm_default(attributes.new, pattern = S("@after_", "Alcohol", 1), extract=TRUE)
attri_Alcohol = unlist(attri_Alcohol)
attri_amb_romantic <- rm_default(attributes.new, pattern = S("@after_", "romantic", 1), extract=TRUE)
attri_amb_romantic = unlist(attri_amb_romantic)
attri_amb_intimate <- rm_default(attributes.new, pattern = S("@after_", "intimate", 1), extract=TRUE)
attri_amb_intimate = unlist(attri_amb_intimate)
attri_amb_classy <- rm_default(attributes.new, pattern = S("@after_", "classy", 1), extract=TRUE)
attri_amb_classy = unlist(attri_amb_classy)
attri_amb_hipster <- rm_default(attributes.new, pattern = S("@after_", "hipster", 1), extract=TRUE)
attri_amb_hipster = unlist(attri_amb_hipster)
attri_amb_divey <- rm_default(attributes.new, pattern = S("@after_", "divey", 1), extract=TRUE)
attri_amb_divey = unlist(attri_amb_divey)
attri_amb_touristy <- rm_default(attributes.new, pattern = S("@after_", "touristy", 1), extract=TRUE)
attri_amb_touristy = unlist(attri_amb_touristy)
attri_amb_trendy <- rm_default(attributes.new, pattern = S("@after_", "trendy", 1), extract=TRUE)
attri_amb_trendy = unlist(attri_amb_trendy)
attri_amb_upscale <- rm_default(attributes.new, pattern = S("@after_", "upscale", 1), extract=TRUE)
attri_amb_upscale = unlist(attri_amb_upscale)
attri_amb_RestaurantsDelivery <- rm_default(attributes.new, pattern = S("@after_", "RestaurantsDelivery", 1), extract=TRUE)
attri_amb_RestaurantsDelivery = unlist(attri_amb_RestaurantsDelivery)
attri_BYOB <- rm_default(attributes.new, pattern = S("@after_", "BYOB", 1), extract=TRUE)
attri_BYOB = unlist(attri_BYOB)
attri_BYOBCorkage <- rm_default(attributes.new, pattern = S("@after_", "BYOBCorkage", 1), extract=TRUE)
attri_BYOBCorkage = unlist(attri_BYOBCorkage)
attri_BikeParking <- rm_default(attributes.new, pattern = S("@after_", "BikeParking", 1), extract=TRUE)
attri_BikeParking = unlist(attri_BikeParking)
attri_BusinessAcceptsBitcoin <- rm_default(attributes.new, pattern = S("@after_", "BusinessAcceptsBitcoin", 1), extract=TRUE)
attri_BusinessAcceptsBitcoin = unlist(attri_BusinessAcceptsBitcoin)
attri_BusinessAcceptsCreditCards <- rm_default(attributes.new, pattern = S("@after_", "BusinessAcceptsCreditCards", 1), extract=TRUE)
attri_BusinessAcceptsCreditCards = unlist(attri_BusinessAcceptsCreditCards)
attri_BusiParking_garage <- rm_default(attributes.new, pattern = S("@after_", "garage", 1), extract=TRUE)
attri_BusiParking_garage = unlist(attri_BusiParking_garage)
attri_BusiParking_street <- rm_default(attributes.new, pattern = S("@after_", "street", 1), extract=TRUE)
attri_BusiParking_street = unlist(attri_BusiParking_street)
attri_BusiParking_validated <- rm_default(attributes.new, pattern = S("@after_", "validated", 1), extract=TRUE)
attri_BusiParking_validated = unlist(attri_BusiParking_validated)
attri_BusiParking_lot <- rm_default(attributes.new, pattern = S("@after_", "lot", 1), extract=TRUE)
attri_BusiParking_lot = unlist(attri_BusiParking_lot)
attri_BusiParking_valet <- rm_default(attributes.new, pattern = S("@after_", "valet", 1), extract=TRUE)
attri_BusiParking_valet = unlist(attri_BusiParking_valet)
attri_ByAppointmentOnly <- rm_default(attributes.new, pattern = S("@after_", "ByAppointmentOnly", 1), extract=TRUE)
attri_ByAppointmentOnly = unlist(attri_ByAppointmentOnly)
attri_Caters <- rm_default(attributes.new, pattern = S("@after_", "Caters", 1), extract=TRUE)
attri_Caters = unlist(attri_Caters)
attri_Corkage <- rm_default(attributes.new, pattern = S("@after_", "Corkage", 1), extract=TRUE)
attri_Corkage = unlist(attri_Corkage)
attri_DogsAllowed <- rm_default(attributes.new, pattern = S("@after_", "DogsAllowed", 1), extract=TRUE)
attri_DogsAllowed = unlist(attri_DogsAllowed)
attri_GoodForKids <- rm_default(attributes.new, pattern = S("@after_", "GoodForKids", 1), extract=TRUE)
attri_GoodForKids = unlist(attri_GoodForKids)
attri_GoodForMeal_dessert <- rm_default(attributes.new, pattern = S("@after_", "dessert", 1), extract=TRUE)
attri_GoodForMeal_dessert = unlist(attri_GoodForMeal_dessert)
attri_GoodForMeal_latenight <- rm_default(attributes.new, pattern = S("@after_", "latenight", 1), extract=TRUE)
attri_GoodForMeal_latenight = unlist(attri_GoodForMeal_latenight)
attri_GoodForMeal_lunch <- rm_default(attributes.new, pattern = S("@after_", "lunch", 1), extract=TRUE)
attri_GoodForMeal_lunch = unlist(attri_GoodForMeal_lunch)
attri_GoodForMeal_dinner <- rm_default(attributes.new, pattern = S("@after_", "dinner", 1), extract=TRUE)
attri_GoodForMeal_dinner = unlist(attri_GoodForMeal_dinner)
attri_GoodForMeal_breakfast <- rm_default(attributes.new, pattern = S("@after_", "breakfast", 1), extract=TRUE)
attri_GoodForMeal_breakfast = unlist(attri_GoodForMeal_breakfast)
attri_GoodForMeal_brunch <- rm_default(attributes.new, pattern = S("@after_", "brunch", 1), extract=TRUE)
attri_GoodForMeal_brunch = unlist(attri_GoodForMeal_brunch)
attri_HasTV <- rm_default(attributes.new, pattern = S("@after_", "HasTV", 1), extract=TRUE)
attri_HasTV = unlist(attri_HasTV)
attri_NoiseLevel <- rm_default(attributes.new, pattern = S("@after_", "NoiseLevel", 1), extract=TRUE)
attri_NoiseLevel = unlist(attri_NoiseLevel)
attri_Open24Hours <- rm_default(attributes.new, pattern = S("@after_", "Open24Hours", 1), extract=TRUE)
attri_Open24Hours = unlist(attri_Open24Hours)
attri_OutdoorSeating <- rm_default(attributes.new, pattern = S("@after_", "OutdoorSeating", 1), extract=TRUE)
attri_OutdoorSeating = unlist(attri_OutdoorSeating)
attri_RestaurantsAttire <- rm_default(attributes.new, pattern = S("@after_", "RestaurantsAttire", 1), extract=TRUE)
attri_RestaurantsAttire = unlist(attri_RestaurantsAttire)
attri_RestaurantsCounterService <- rm_default(attributes.new, pattern = S("@after_", "RestaurantsCounterService", 1), extract=TRUE)
attri_RestaurantsCounterService = unlist(attri_RestaurantsCounterService)
attri_RestaurantsGoodForGroups <- rm_default(attributes.new, pattern = S("@after_", "RestaurantsGoodForGroups", 1), extract=TRUE)
attri_RestaurantsGoodForGroups = unlist(attri_RestaurantsGoodForGroups)
attri_RestaurantsPriceRange2 <- rm_default(attributes.new, pattern = S("@after_", "RestaurantsPriceRange2", 1), extract=TRUE)
attri_RestaurantsPriceRange2 = unlist(attri_RestaurantsPriceRange2)
attri_RestaurantsReservations <- rm_default(attributes.new, pattern = S("@after_", "RestaurantsReservations", 1), extract=TRUE)
attri_RestaurantsReservations = unlist(attri_RestaurantsReservations)
attri_RestaurantsTableService <- rm_default(attributes.new, pattern = S("@after_", "RestaurantsTableService", 1), extract=TRUE)
attri_RestaurantsTableService = unlist(attri_RestaurantsTableService)
attri_RestaurantsTakeOut <- rm_default(attributes.new, pattern = S("@after_", "RestaurantsTakeOut", 1), extract=TRUE)
attri_RestaurantsTakeOut = unlist(attri_RestaurantsTakeOut)
attri_WheelchairAccessible <- rm_default(attributes.new, pattern = S("@after_", "WheelchairAccessible", 1), extract=TRUE)
attri_WheelchairAccessible = unlist(attri_WheelchairAccessible)
attri_WiFi <- rm_default(attributes.new, pattern = S("@after_", "WiFi", 1), extract=TRUE)
attri_WiFi = unlist(attri_WiFi)
attri_DietaryRestrictions_dairyfree <- rm_default(attributes.new, pattern = S("@after_", "dairyfree", 1), extract=TRUE)
attri_DietaryRestrictions_dairyfree = unlist(attri_DietaryRestrictions_dairyfree)
attri_DietaryRestrictions_glutenfree <- rm_default(attributes.new, pattern = S("@after_", "glutenfree", 1), extract=TRUE)
attri_DietaryRestrictions_glutenfree = unlist(attri_DietaryRestrictions_glutenfree)
attri_DietaryRestrictions_vegan <- rm_default(attributes.new, pattern = S("@after_", "vegan", 1), extract=TRUE)
attri_DietaryRestrictions_vegan = unlist(attri_DietaryRestrictions_vegan)
attri_DietaryRestrictions_kosher <- rm_default(attributes.new, pattern = S("@after_", "kosher", 1), extract=TRUE)
attri_DietaryRestrictions_kosher = unlist(attri_DietaryRestrictions_kosher)
attri_DietaryRestrictions_halal <- rm_default(attributes.new, pattern = S("@after_", "halal", 1), extract=TRUE)
attri_DietaryRestrictions_halal = unlist(attri_DietaryRestrictions_halal)
attri_DietaryRestrictions_soyfree <- rm_default(attributes.new, pattern = S("@after_", "soyfree", 1), extract=TRUE)
attri_DietaryRestrictions_soyfree = unlist(attri_DietaryRestrictions_soyfree)
attri_DietaryRestrictions_vegetarian <- rm_default(attributes.new, pattern = S("@after_", "vegetarian", 1), extract=TRUE)
attri_DietaryRestrictions_vegetarian = unlist(attri_DietaryRestrictions_vegetarian)

mydata = cbind(attri_Alcohol, attri_amb_romantic, attri_amb_intimate, attri_amb_classy, attri_amb_hipster, attri_amb_divey, attri_amb_touristy, attri_amb_trendy, attri_amb_upscale, attri_RestaurantsAttire, attri_BYOB, attri_BYOBCorkage, attri_BikeParking, attri_BusinessAcceptsBitcoin, attri_BusinessAcceptsCreditCards, attri_BusiParking_garage, attri_BusiParking_street, attri_BusiParking_validated, attri_BusiParking_lot, attri_BusiParking_valet, attri_ByAppointmentOnly, attri_Caters, attri_Corkage, attri_DogsAllowed, attri_GoodForKids, attri_GoodForMeal_dessert, attri_GoodForMeal_latenight, attri_GoodForMeal_lunch, attri_GoodForMeal_dinner, attri_GoodForMeal_breakfast, attri_GoodForMeal_brunch, attri_HasTV, attri_NoiseLevel, attri_Open24Hours, attri_OutdoorSeating, attri_amb_RestaurantsDelivery, attri_RestaurantsCounterService, attri_RestaurantsGoodForGroups, attri_RestaurantsPriceRange2, attri_RestaurantsReservations, attri_RestaurantsTableService, attri_RestaurantsTakeOut, attri_WheelchairAccessible, attri_WiFi, attri_DietaryRestrictions_dairyfree, attri_DietaryRestrictions_glutenfree, attri_DietaryRestrictions_vegan, attri_DietaryRestrictions_kosher, attri_DietaryRestrictions_halal, attri_DietaryRestrictions_soyfree, attri_DietaryRestrictions_vegetarian)
write.csv(mydata, file = "xxx.csv")







